# Generated by Django 4.1.7 on 2023-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[[1, '*'], [2, '**'], [3, '***'], [4, '****'], [5, '*****']], default=1),
        ),
    ]
